# version: "3.8"
services:
  redis:
    image: "redis"
    env_file: ./.env
    ports:
      - "6379:6379"
    networks:
      - tool_network

  postgres:
    image: "postgres:17"
    env_file: ./.env
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: mydatabase

    ports:
      - "5432:5432"
    networks:
      - tool_network

      
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file: ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - tool_network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  worker:
    build: .
    command: celery -A tasks.tasks worker --loglevel=info
    env_file: ./.env
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
    networks:
      - tool_network

  celery-beat:
    build: .
    command: celery -A tasks.tasks beat --loglevel=info
    # command: celery -A tasks.tasks beat --loglevel=info --scheduler django-celery
    # command: celery -A tasks.tasks beat --scheduler celery.beat.PersistentScheduler --loglevel=info
    env_file: ./.env
    depends_on:
      - redis
      - web
      - worker
    volumes:
      - .:/app
    networks:
      - tool_network

networks:
  tool_network:
    driver: bridge


# version: "3.8"
# services:
#   redis:
#     image: "redis"
#     ports:
#       - "6379:6379"
#     networks:
#       - tool_network

#   postgres:
#     image: "postgres:17"
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     networks:
#       - tool_network

#   web:
#     build: .
#     command: uvicorn main:app --host 0.0.0.0 --port 8000
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#       - postgres
#     networks:
#       - tool_network

#   worker:
#     build: .
#     command: celery -A tasks worker --loglevel=info
#     depends_on:
#       - redis
#       - postgres
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=db+postgresql://myuser:mypassword@postgres:5432/mydatabase
#     volumes:
#       - .:/app
#     networks:
#       - tool_network

#   celery-beat:
#     build: .
#     command: celery -A tasks beat --loglevel=info
#     depends_on:
#       - redis
#       - worker
#       - postgres
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=db+postgresql://myuser:mypassword@postgres:5432/mydatabase
#     networks:
#       - tool_network

# networks:
#   tool_network:
#     driver: bridge
