# version: "3.8"
services:
#  redis:
#    image: "redis"
#    env_file: ./.env
#    ports:
#      - "6379:6379"
#    networks:
#      - tool_network

  postgres:
    image: "postgres"
    env_file: ./.env
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: mydatabase

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - tool_network

      
  web:
    build: .
    tty: true      # Enables TTY
    stdin_open: true  # Keeps stdin open
    command: /bin/sh -c "tmux new-session -d -s app 'uvicorn main:app --host 0.0.0.0 --port 8000' && tmux attach"
#    command: python main.py
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
    # command: tmux new-session -d -s scheduler 'uvicorn main:app --host 0.0.0.0 --port 8000' && tmux split-window -v 'tmux capture-pane -p -S -' && tmux attach-session -t scheduler

    env_file: ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - tool_network
   
#  worker:
#    build: .
#    command: celery -A tasks.tasks worker --loglevel=info
#    env_file: ./.env
#    depends_on:
#      - redis
#      - web
#    volumes:
#      - .:/app
#    networks:
#      - tool_network
#
#  celery-beat:
#    build: .
#    command: celery -A tasks.tasks beat --loglevel=info
#    env_file: ./.env
#    depends_on:
#      - redis
#      - web
#      - worker
#    volumes:
#      - .:/app
#    networks:
#      - tool_network

networks:
  tool_network:
    driver: bridge

volumes:
  postgres_data: